# Generated by Django 4.2.9 on 2024-11-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
